stages:
  - testsuite

testsuite:debian:
  image: debian
  stage: testsuite
  script:
    - apt-get -qqy update
    - apt-get -qqy install --no-install-recommends php-dev gcc make
    - make debug

testsuite:fedora:
  image: fedora
  stage: testsuite
  script:
    - dnf install -y php-devel gcc make
    - make debug

testsuite:ubuntu:
  image: ubuntu
  stage: testsuite
  script:
    - apt-get -qqy update
    - DEBIAN_FRONTEND=noninteractive apt-get -qqy install --no-install-recommends php-dev gcc make
    - make debug

#testsuite:alpine:
#  image: alpine
#  stage: testsuite
#  script:
#    - apk update
#    - apk add php7-dev make gcc musl-dev
#    - make debug
