language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_install:
  - pip install --user cpp-coveralls

script:
  - cd src
  - phpize
  - ./configure --enable-snuffleupagus --enable-coverage
  - make
  - make test

after_success:
  - git clone https://github.com/linux-test-project/lcov.git --depth 1
  - rm -rf ./lcov/examples/ ./lcov/test/
  - ./lcov/bin/lcov -c -o ./COV.info --rc lcov_branch_coverage=1 --base-directory . --directory .
  - ./lcov/bin/lcov --remove ./COV.info '/usr/*' --remove ./COV.info '*tweetnacl.c' -o ./COV.info --rc lcov_branch_coverage=1
  - ./lcov/bin/genhtml -o ./COV.html ./COV.info  --branch-coverage
  - coveralls --exclude 'tweetnacl.c'
